# Generated by Django 5.0.6 on 2024-07-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='css_file',
            field=models.FileField(blank=True, null=True, upload_to='page_css/'),
        ),
        migrations.AddField(
            model_name='page',
            name='redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
