# Generated by Django 5.0.6 on 2025-01-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_page_css_file_page_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dedicatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado?')),
            ],
        ),
    ]
