# Generated by Django 5.0.6 on 2025-02-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_dedicatoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='dedicatoria',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dedicatorias/'),
        ),
    ]
