# Generated by Django 5.0.6 on 2024-12-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='divorced_parent',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='partner',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
