# Generated by Django 5.0.6 on 2024-11-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0002_alter_relationship_child_alter_relationship_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='divorced_parent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='partner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
