# Generated by Django 5.0.6 on 2025-01-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0003_alter_relationship_child_alter_relationship_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='divorced_parent',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='partner',
        ),
        migrations.AddField(
            model_name='familymember',
            name='info',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
    ]
