# Generated by Django 5.0.6 on 2025-01-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0004_remove_familymember_divorced_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='info',
            field=models.TextField(blank=True, db_index=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='name',
            field=models.CharField(db_index=True, max_length=1000),
        ),
    ]
