# Generated by Django 5.0.6 on 2025-01-25 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0005_dedicatoria_alter_familymember_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dedicatoria',
        ),
    ]
