# Generated by Django 5.0.6 on 2025-01-26 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0005_alter_familymember_id_alter_familymember_info_and_more'),
        ('familytree', '0006_delete_dedicatoria'),
    ]

    operations = [
    ]
