# Generated by Django 5.0.6 on 2025-01-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0007_merge_20250126_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='name',
            field=models.CharField(db_index=True, max_length=400),
        ),
    ]
